config/routes.rb
Rails.application.routes.draw do

  resources :search
  devise_for :users
  resources :users
  get "home/index"
  root "home#index"

  get 'calc/index', :to => 'calc#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # belongs_to :userable, polymorphic: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  helper_method :redirect_back

  def redirect_back(options = {})
    if request.referer
      redirect_to request.referer, options
    else
      redirect_to root_path, options
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :location, :compnay_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :location, :company_name])
  end
end

app/controllers/calc_controller.rb
class CalcController < ApplicationController
    def index
  
    end

    def calc_params
      params.require(:post).permit(:materials, :pounds, :user_id)
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # @posts = Post.all
    
    # @post = Post.find_by(params[:id])
    # @user = current_user

    # @comments = Comment.all
    # @comment = Comment.new

    if params[:search]
      @posts = Post.where('topic LIKE ?', "%#{params[:search]}%")
    else
      @user = current_user
      @posts = Post.all
    end
  end
    
  def show
    @user = current_user
    @comment = Comment.new
    @post = Post.find(params[:id])
    @like_count = Like.where(post_id: params[:id]).count
    @is_user_liked = Like.where(user_id: @user.id, post_id: params[:id]).count != 0
    @like = Like.new()
  end

  def new
    @post = Post.new

    

    @user = current_user
  end

  def edit
    @post = Post.find(params[:id])
    # @user = User.find_by(params[:id])
    @user = current_user
  end

  def create
    @post = Post.new(post_params)

    @user = current_user


    if @post.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @post = Post.find(params[:id])
	
    if @post.update_attributes(post_params)
       redirect_to :action => 'show', :id => @post
    else
       render :action => 'edit'
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to :action => 'index'
  end
  
  private

  def post_params
    params.require(:post).permit(:materials, :pickup_location, :start_time, :pounds, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show


    @user = current_user


  end

  private


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calc/index.html.erb
<div class="container">
<h1>Header</h1>
<%= bootstrap_form_with(model: @post, local: true) do |f| %>
<div class="top-m">
<p>Hello</p>
  <form>
                <div class="row" style="border: solid black 2px; padding: 5px 0 5px 0; border-radius: 15px 50px;background-image: linear-gradient(to right, #72A82B 0%, #A7FA65 100%); box-shadow: 5px 5px 3px grey; color:white; padding: 5px 5px 5px 20px; text-shadow: 2px 2px 0px black;">
                    <div class="col-md-6">
                        <div class="form-group">
                          <%= f.select :materials, ["Paper", "Plastic", "Metals"], label: "Materials:" %>
                        </div>
                        <div class="form-group">
                          <%= f.select :pounds, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ], label: "Lbs:" %>
                        </div>
                      
                    <div class="col-md-12">
                    <%= f.submit({:class=> 'btn btn-dark'}) %>
                    </div>
                </div>
                </form>
</div>
 <% end %>
</div>

app/views/home/index.html.erb
<br><br><br><br><br><br><br><br>

<p>Welcome To RECYCLER!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recycler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Fredoka+One", "application" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>

  <div id="flipkart-navbar" style="background-image: linear-gradient(to right, #72A82B 0%, #A7FA65 100%); box-shadow: 5px 5px 3px grey;">
    
     <span>
    <%= link_to image_tag("relogo.png"), home_index_path, style: "margin-top:5px; position:absolute; padding-left:40px;"%>
    </span>
    
    <div class="container">
        <nav class="row row1 stroke">
            <ul class="largenav pull-right">
                <li class="upper-links "><%= link_to "Home", home_index_path, class: "links" %></li>
                <li class="upper-links "><%= link_to "Calculate", calc_index_path, class: "links" %></li>

                <li class="upper-links">
                </li>
                <li class="upper-links dropdown"><a class="links2" href="#">Orders</a>
                    <ul class="dropdown-menu">
                        <li class="profile-li"><%= link_to "New", new_post_path, class: "links" %></li>
                         <li class="profile-li"><%= link_to "All Orders", posts_path, class: "links" %></li>
                    </ul>
                </li>
                   <li class="upper-links dropdown"><a class="links2" href="#">Account</a>
                    <ul class="dropdown-menu">
                        <li class="profile-li"><%= link_to "View Profile", current_user, class: "links" %></li>
                        <li class="profile-li"><%= link_to "Account Settings", edit_user_registration_path, class: "links" %></li>
                        <li class="profile-li"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "links" %></li>
                    </ul>
                </li>
                   
               
            </ul>
        </nav>
        <div class="row">
            <div class="col-sm-2">
                <h2 style="margin:0px;"><span class="smallnav menu" onclick="openNav()">☰ Adulting</span></h2>
            
            </div>
           
       <!--<div class="container">
  <button class="btn btn-default btn-sm btn-link links" style="font-size:30px;">
    <span class="glyphicon glyphicon-bullhorn"></span>
  </button>
  <span class="badge badge-notify">3</span>
</div>-->
        </div>
    </div>
</div>

<%= yield %>


<!-- Footer -->

<!-- Footer -->

  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
<%= bootstrap_form_with(model: @post, local: true) do |f| %>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="well well-sm top-m2">
                <form>
                <div class="row">
                    <div class="col-md-6">
                        
                             <div class="form-group">
                          <%= f.select :materials, ["Paper", "Plastic", "Metals"], label: "Materials:" %>
                        </div>
                        <div class="form-group">
                          <%= f.select :pounds, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ], label: "Lbs:" %>
                        </div>
                        <div class="form-group">
                            <%= f.text_field :pickup_location, label: "Pickup Location:" %>
                        </div>
                       <div class="form-group">
                            <%= f.date_select :pickup_time, label: "Pickup Time:" %>
                            <%= f.hidden_field(:user_id, value: "#{@user.id}") %>
                        </div>
                    <div class="col-md-12">
                    <%= f.submit({:class=> 'btn btn-outline-primary'}) %>
                    </div>
                </div>
                </form>
            </div>
        </div>
       
    </div>
    <% end %>
</div>



 

app/views/posts/index.html.erb
<div class="container">
  <h1 class="header"></h1>

    <!-- START BASIC TABLE SAMPLE -->
                            <div class="panel panel-default">
                                <div class="panel-heading top-m3">
                                    <h3 class="panel-title">Open Orders</h3>
                                </div>
                                <div class="panel-body">
                                    <p>These orders have not been picked up yet...</p>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Order Number</th>
                                                <th>Materials</th>
                                                <th>Pickup Location</th>
                                                <th>Pickup Time</th>
                                                <th>Pounds</th>
                                                <th>Edit Order</th>
                                            </tr>
                                        </thead>
                                         <% @posts.reverse.each do |post| %>
                                        <tbody>
                                            <tr>
                                                <td><%= post.id %></td>
                                                <td><%= post.materials %></td>
                                                <td><%= post.pickup_location %></td>
                                                <td><%= post.start_time.strftime("%I:%M %p") %></td>
                                                <td><%= post.pounds %></td>
                                                <td ><%= link_to "View Post", post, class: "btn btn-outline-danger" %></td>

                                            </tr>
                                        </tbody>
                                        <% end %>
                                    </table>                                
                                </div>
                            </div>
                             
                            <!-- END BASIC TABLE SAMPLE -->

<%= month_calendar events: @posts do |date, posts| %>
  <%= date %>

  <% posts.each do |post| %>
  <br>
    <strong style="color:green;">
      <%= post.start_time.strftime("%I:%M %p") %>
    </strong>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<div class="container">
<%= bootstrap_form_with(model: @post, local: true) do |f| %>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="well well-sm top-m2">
                <form>
                <div class="row" style="border: solid black 2px; padding: 5px 0 5px 0; border-radius: 15px 50px;background-image: linear-gradient(to right, #72A82B 0%, #A7FA65 100%); box-shadow: 5px 5px 3px grey; color:white; padding: 5px 5px 5px 20px; text-shadow: 2px 2px 0px black;">
                    <div class="col-md-6">
                        
                             <div class="form-group">
                          <%= f.select :materials, ["Paper", "Plastic", "Metals"], label: "Materials:" %>
                        </div>
                        <div class="form-group">
                          <%= f.select :pounds, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ], label: "Lbs:" %>
                        </div>
                        <div class="form-group">
                            <%= f.text_field :pickup_location, label: "Pickup Location:" %>
                        </div>
                       <div class="form-group">
                            <%= f.datetime_select :start_time, label: "Pickup Time:" %>
                            <%= f.hidden_field(:user_id, value: "#{@user.id}") %>
                        </div>
                    <div class="col-md-12">
                    <%= f.submit({:class=> 'btn btn-dark'}) %>
                    </div>
                </div>
                </form>
            </div>
        </div>
       
    </div>
    <% end %>
</div>



 

app/views/posts/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 top-m">
      <h1 class="mt-4">Location: <%= @post.pickup_location %></h1>
          <p class="lead">
            Topic:
           
          </p>
            <p class="lead">
            Company Name:
            <%= @post.user.company_name %><br>
            <% if @post.user_id == current_user.id %>
              <%= link_to 'Delete this post. ', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %><br>
              <%= link_to 'Edit this post. ', edit_post_path(@post) %>
            <% end %>
          </p>

          <hr>
          <p>Created <%= time_ago_in_words(@post.created_at) %> ago.</p>
          <hr>
     
          <hr>
          Materials: <%= @post.materials %> 
          <br>
          Pickup Location: <%= @post.pickup_location %>
          <br>
          Pickup Time: <%= @post.start_time.strftime("%I:%M %p") %>
          <br>
          Lbs: <%= @post.pounds %>
          <hr>
       
      </div>
  </div>
</div>

app/views/users/_user.html.erb
<td><%= link_to "#{user.last_name} #{user.first_name}", user %></td>
<td><%= link_to user.username, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="container">

<div class="row">
<div class="d-flex flex-wrap top-m3">

</div>
</div>
</div>
<div class="row col-12-sm">
   <% @user.posts.reverse.each do |post| %>
     <div class="topiko-caro row">
       <div class="d-flex flex-wrap">
         <div class="card shift shadow-lg p-3 mb-5 bg-white rounded" style="width: 20rem;">
           <div class="pulsated">
            
               <div class="avatar">
                
               </div>
           </div>
           <div class="card-body">
             <p class="post-meta">
             
               <h5 class="card-title card-dark" style="color:blue;">
                 Pickup date: <%= post.start_time.strftime("%b %e, %l:%M %p") %>
               </h5>
               <p class="card-text">
                 Pickup location: <%= post.pickup_location %>
               </p>
               <p class="card-text">
                 Lbs: <%= post.pounds %>
               </p>
               <p class="card-text">
                 Material: <%= post.materials %>
               </p>
                 <span class="published">Order placed <%= time_ago_in_words(post.created_at) %> ago:</span>
               <span class="meta-separator post-meta"></span>
               <span h7 class="card-title">
                 <%= link_to post.user.username, current_user %>
               </span><br>
               
                 <%= link_to "View Order", post, class: "btn btn-outline-primary" %>
              
           </div>
         </div>
       </div>
     </div>
<% end %>